version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean-hexagonal-onion-service
    ports:
      - "5432:5432"
    network_mode: "bridge"